name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    # Kör workflowet på senaste Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Hämtar koden från GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Installerar Java (Temurin JDK 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Bygger projektet med Maven
      - name: Build with Maven
        run: mvn clean package

      # Loggar in på Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bygger Docker-image
      - name: Build Docker image
        run: docker build -t theonelinkan/spring-dice-app:latest .

      # Pushar Docker-image till Docker Hub
      - name: Push Docker image
        run: docker push theonelinkan/spring-dice-app:latest